name: app_ui
description: "UI Toolkit."
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  spider: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  assets:
    - assets/
    - assets/image/background/

  fonts:
    - family: Newake
      fonts:
        - asset: assets/fonts/Newake-Font.otf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 200
          style: italic
